### ISSUE TITLE
Why are not all transactions displayed?

### ISSUE THREAD

**Issue by Sunkist228** [no-name-user-name/pyTelegramWalletApi#15]
Why are not all the transactions displayed? Only those above 94.54 rubles are shown, even though there are cheaper ones available.

**Comment by no-name-user-name** [comment]
a y menya vse ok. v telegu pishi esli 4to

**Comment by Sunkist228** [comment]
OK. Poprobuyu poka chto sam razobrat'sa. Esli chto napishu.
